[build]
builder = "NIXPACKS"
buildCommand = "python -m pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn line_bot:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
